apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-service
  labels:
    app: converter-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: converter-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8  
  template:
    metadata:
      labels:
        app: converter-service
    spec:
      containers:
        - name: converter-service
          image: prosperibe12/converter-service
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret