# Configuration file for the converter-service Helm chart

# Deployment name override
projectNameOverride: converter

# Common labels for deployment
commonLabels:
  app: converter
  tier: backend

# Selector labels for the deployment
selectorLabels:
  app: converterapi

# Replica count for the deployment
replicaCount: 3

# Strategy for the deployment
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

# Image configuration
image:
  name: converterapp
  repository: prosperibe12/converter-service
  tag: latest
  pullPolicy: Always
  containerPort: 8000

# Resources for the deployment
resources: {}
  # limits: 
  #   cpu: "400m"
  #   memory: "512Mi"
  # requests:
  #   cpu: "200m"
  #   memory: "256Mi"

# ConfigMap configuration
config:
  VIDEO_QUEUE: "videos"
  MP3_QUEUE: "mp3" 
  RABBITMQ_HOST: "rabbitmq-svc"
  RABBITMQ_PORT: "5672"
  MONGODB_HOST: "mongodb-svc"




# Service configuration
service:
  type: ClusterIP
  ports:
    - port: 2000
      targetPort: 2000
      protocol: TCP

# Horizontal Pod Autoscaler configuration
autoscaling:
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

